name: Build docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "build docker image"
      run: |
        make build

    - name: "print version informations"
      run: |
        make micropython_version
        make mpy_cross_version

  release:
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build
    steps:
      - uses: actions/checkout@v1

      - name: "push image to docker hub"
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push jedie/micropython;
